---
# tasks file for role-cardano-node
- name: Set cardano node directory
  set_fact:
    cardano_node_dir: "{{ ansible_env.HOME }}/cardano-node"
- name: Download cardano node
  git:
    repo: https://github.com/input-output-hk/cardano-node.git
    dest: "{{ cardano_node_dir }}"
    version: "{{ cardano_node_version }}"
- name: Build cardano node
  shell: "{{ ansible_env.HOME }}/.nix-profile/bin/nix build .#mainnet/node -o mainnet-node-local"
  args:
    chdir: "{{ cardano_node_dir }}"
