---
# tasks file for role-cardano-node
- name: Set cardano node directory
  set_fact:
    cardano_node_dir: "{{ ansible_env.HOME }}/cardano-node"
- name: Download cardano node
  git:
    repo: https://github.com/input-output-hk/cardano-node.git
    dest: "{{ cardano_node_dir }}"
    version: "{{ cardano_node_version }}"
- name: Build cardano node
  shell: "{{ ansible_env.HOME }}/.nix-profile/bin/nix build .#mainnet/node -o mainnet-node-local"
  args:
    chdir: "{{ cardano_node_dir }}"
- name: Build cardano node testnet
  shell: "{{ ansible_env.HOME }}/.nix-profile/bin/nix build .#testnet/node -o testnet-node-local"
  args:
    chdir: "{{ cardano_node_dir }}"
- name: Create cardano node service
  copy:
    src: cardano-node.service
    dest: /etc/systemd/system/
  become: yes
- name: Create cardano node testnet service
  copy:
    src: cardano-node-testnet.service
    dest: /etc/systemd/system/
  become: yes
- name: Enable cardano node service
  systemd:
    name: cardano-node
    enabled: yes
  become: yes
- name: Build cardano cli
  shell: "{{ ansible_env.HOME }}/.nix-profile/bin/nix build .#cardano-cli -o cardano-cli-build"
  args:
    chdir: "{{ cardano_node_dir }}"
