---
# tasks file for role-cardano-node
- name: Set cardano node directory
  set_fact:
    cardano_node_dir: "{{ ansible_env.HOME }}/cardano-node"
- name: Download cardano node
  git:
    repo: https://github.com/input-output-hk/cardano-node.git
    dest: "{{ cardano_node_dir }}"
    version: "{{ cardano_node_version }}"
- name: Build cardano node
  shell: "{{ shell_only_nix_build }} .#mainnet/node -o mainnet-node-local"
  args:
    chdir: "{{ cardano_node_dir }}"
- name: Build cardano node testnet
  shell: "{{ shell_only_nix_build }} .#testnet/node -o testnet-node-local"
  args:
    chdir: "{{ cardano_node_dir }}"
- name: Create cardano node service
  ansible.builtin.template:
    src: cardano-node.service.j2
    dest: /etc/systemd/system/cardano-node.service
  become: yes
- name: Create cardano node testnet service
  ansible.builtin.template:
    src: cardano-node-testnet.service.j2
    dest: /etc/systemd/system/cardano-node-testnet.service
  become: yes
- name: Enable cardano node service
  systemd:
    name: cardano-node
    enabled: yes
  become: yes
- name: Build cardano cli
  shell: "{{ shell_only_nix_build }} .#cardano-cli -o cardano-cli-build"
  args:
    chdir: "{{ cardano_node_dir }}"
