apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pipelinerun.yaml
configurations:
- kustomizeconfig.yaml
secretGenerator:
- name: aws
  files:
  - credentials=secret/awsCredentials.txt
  - config=secret/awsConfig.txt
