apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: packer-cardano-node-pipelinerun
spec:
  pipelineSpec:
    tasks:
    - name: git-clone-packer
      params:
      - name: url
        value: https://github.com/whslabs/packer-cardano-node.git
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: outputs
        subpath: output-packer
    - name: git-clone-boto3
      params:
      - name: url
        value: https://github.com/whslabs/boto3_delete_old_amis.git
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: outputs
        subpath: output-boto3
    - name: build-packer
      runAfter: [git-clone-packer]
      taskSpec:
        steps:
        - name: build
          image: nix
          script: |
            #!/usr/bin/env sh
            cd $(workspaces.input.path)
            ./build.sh
        workspaces:
        - name: aws
          mountPath: /root/.aws/
        - name: input
      workspaces:
      - name: aws
        workspace: aws
      - name: input
        workspace: outputs
        subpath: output-packer
    - name: build-boto3
      runAfter:
      - build-packer
      - git-clone-boto3
      taskSpec:
        steps:
        - name: build
          image: python
          script: |
            #!/usr/bin/env sh
            curl \
              -L \
              -O \
              https://github.com/bazelbuild/bazelisk/releases/download/v1.12.0/bazelisk-linux-amd64
            install bazelisk-linux-amd64 /usr/local/bin/bazelisk
            cd $(workspaces.input.path)
            bazelisk run //:boto3_delete_old_amis_bin
        workspaces:
        - name: aws
          mountPath: /root/.aws/
        - name: input
      workspaces:
      - name: aws
        workspace: aws
      - name: input
        workspace: outputs
        subpath: output-boto3
    workspaces:
    - name: aws
    - name: outputs
  workspaces:
  - name: outputs
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce
  - name: aws
    secret:
      secretName: aws
